# Generated by Django 5.2 on 2026-09-22 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0003_alter_event_capacity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Liveact'},
        ),
    ]
