# Generated by Django 5.2 on 2026-09-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings_app', '0002_participant_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(help_text='test@test.de', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='first_name',
            field=models.CharField(help_text='Onley first Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='participant',
            name='last_name',
            field=models.CharField(help_text='Onley last Name', max_length=100),
        ),
    ]
